id: I409E1122
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:06:05+00:00'
last_modified: '2022-06-08T05:05:44.869123+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25126
  title: གཉིད་དང་རྨི་ལམ་བར་གྱི་འབྲེལ་བ་རྣམ་པར་དཔྱད་པ་ཌཱ་ཀིའི་གླུ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    83D0:
      image_group_id: I1KG10372
      title: ''
      total_pages: 420
      order: 1
      base_file: 83D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
